import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const amazonEmber = localFont({
  src: [
    {
      path: './fonts/AmazonEmber_Rg.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/AmazonEmber_Bd.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-amazon-ember', // Optional: For Tailwind integration
});

export const metadata: Metadata = {
  title: "AWS Cloud Club — Haribon", // Use the actual em dash
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${amazonEmber.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
